### ISSUE TITLE
Docker image way too large

### ISSUE THREAD

**Issue by arthur-c** [logmatic/logmatic-docker#3]
Hi,

The logmatic docker takes 644.7 MB. It's way too large for a simple js script (and for a docker). The node docker is not optimized at all.

I'm able to record my logs with a 28.26 MB logmatic docker !

My Dockerfile:

```
FROM alpine:latest
RUN apk -U add nodejs
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
RUN npm install
COPY . /usr/src/app
ENTRYPOINT ["/usr/src/app/index.js"]
CMD []
```

and it works:

```
Mar 29 19:05:48.699     [Docker event] host="logmatik" name="logmatik" event="kill"
Mar 29 19:05:47.933     [Docker event] host="logmatik" name="logmatik" event="kill"
Mar 29 19:05:14.877     [Docker event] host="alpine" name="evil_curie" event="die"
Mar 29 19:05:12.960     [Docker event] host="alpine" name="evil_curie" event="attach"
Mar 29 19:05:12.832     [Docker event] host="alpine" name="evil_curie" event="start"
Mar 29 19:05:12.832     [Docker event] host="alpine" name="evil_curie" event="attach"
Mar 29 19:05:12.691     [Docker event] host="alpine" name="evil_curie" event="create"
```

**Comment by gpolaert** [comment]
Hi Arthur,

Sure, using Alpine is a good fit, don't hesitate to create a pull request.
Today, I'm working on that image in order to add a container stat event.

Bye

**Comment by gpolaert** [comment]
You can test it of you want, use `docker pull logmatic/logmatic-docker:latest` to force the pull.
The new image size is 28MB now ;)

```
logmatic-m                   latest              67f9f259697c        9 minutes ago       28.26 MB
```

**Comment by arthur-c** [comment]
The image has not been pushed to the dockerhub yet :) https://hub.docker.com/r/logmatic/logmatic-docker/
